/* No fetch, XHR, beacon, storage, audio reads or file mutations. */
'use strict';
const $=id=>document.getElementById(id);
let parsed=null,report=null,readGeneration=0,folderPaths=[],filePaths=[],metadataLabel='pasted metadata';
if(location.protocol==='file:')$('offline-download').hidden=true;
function invalidate(){report=null;$('results').hidden=true;$('error').textContent='';$('export-status').textContent='';}
function resetParse(){readGeneration++;parsed=null;$('column').replaceChildren(new Option('Read the columns first',''));$('column').disabled=true;$('parse-status').textContent='';invalidate();}
function err(e){$('error').textContent=e.message||String(e);}
$('metadata').addEventListener('input',()=>{metadataLabel='pasted metadata';resetParse();});$('delimiter').addEventListener('change',resetParse);
$('metadata-file').addEventListener('change',async()=>{resetParse();$('metadata').value='';metadataLabel='pasted metadata';const generation=readGeneration,file=$('metadata-file').files[0];if(!file)return;try{if(file.size>5000000)throw new Error('Metadata file exceeds 5 MB.');const text=new TextDecoder('utf-8',{fatal:true}).decode(await file.arrayBuffer());if(generation!==readGeneration)return;$('metadata').value=text;metadataLabel=file.name;$('parse').click();}catch(e){err(e);}});
$('parse').addEventListener('click',()=>{invalidate();try{parsed=ReleasePack.parseDelimited($('metadata').value,$('delimiter').value==='tab'?'\t':',');if(parsed.errors.length)throw new Error(parsed.errors.join('\n'));$('column').replaceChildren(new Option('Choose the filename column',''),...parsed.headers.map((h,i)=>new Option(`${i+1}. ${h}`,String(i))));$('column').disabled=false;$('parse-status').textContent=`Read ${parsed.rows.length} metadata records and ${parsed.headers.length} columns. Choose the filename column explicitly.`;}catch(e){parsed=null;$('column').disabled=true;err(e);}});
['column','mode','manifest'].forEach(id=>$(id).addEventListener(id==='manifest'?'input':'change',invalidate));
$('inventory-source').addEventListener('change',()=>{invalidate();const value=$('inventory-source').value;['manifest','folder','files'].forEach(s=>$(s+'-box').hidden=s!==value);$('inventory-status').textContent='';});
$('folder').addEventListener('change',()=>{invalidate();folderPaths=Array.from($('folder').files,f=>f.webkitRelativePath.split('/').slice(1).join('/'));$('inventory-status').textContent=`${folderPaths.length} entries selected. Paths start inside the chosen folder.`;});
$('files').addEventListener('change',()=>{invalidate();filePaths=Array.from($('files').files,f=>f.name);$('inventory-status').textContent=`${filePaths.length} entries selected using basenames only.`;});
function addRow(target,values){const tr=document.createElement('tr');for(const value of values){const td=document.createElement('td');td.textContent=String(value??'');tr.append(td);}target.append(tr);}
$('compare').addEventListener('click',()=>{invalidate();try{if(!parsed||$('column').value==='')throw new Error('Read metadata and choose its filename column first.');const source=$('inventory-source').value;let paths=source==='folder'?folderPaths:source==='files'?filePaths:$('manifest').value.split(/\r\n|\n|\r/);if(source==='manifest'&&paths[paths.length-1]==='')paths.pop();report=ReleasePack.reconcile(parsed,paths,Number($('column').value),$('mode').value);report.inventorySource=source;report.metadataInputName=metadataLabel;$('summary').textContent=`${report.counts.metadataRows} records · ${report.counts.inventoryEntries} file entries · ${report.counts.heldRows} held records · ${report.counts.issues} issues`;$('issues').replaceChildren();for(const issue of report.issues)addRow($('issues'),[issue.code,issue.message,issue.rowIds.join(', ')||'—',issue.fileIds.join(', ')||'—']);if(!report.issues.length)addRow($('issues'),['No filename issues recorded','This does not establish content quality or release approval.','','']);$('rows').replaceChildren();for(const row of report.rows)addRow($('rows'),[`${row.record} / ${row.line}`,row.filename,row.status,row.matchedPath||'unresolved']);$('results').hidden=false;const unsupported=ReleasePackExport.pdfUnsupported(report);$('pdf').disabled=unsupported.length>0;$('pdf-limit').textContent=unsupported.length?'Direct PDF unavailable for these font characters: '+unsupported.map(c=>`${c} (U+${c.codePointAt(0).toString(16).toUpperCase()})`).join(', ')+'. XLSX and JSON retain them unchanged. No incomplete PDF is produced.':'';}catch(e){report=null;err(e);}});
function outputName(){function part(id){const v=$(id).value.replace(/ /g,'_');if(!/^[A-Za-z0-9_-]{1,60}$/.test(v))throw new Error('Vendor and library output names need 1–60 letters, numbers, hyphens or underscores.');return v;}return `${part('vendor-name')}_${part('library-name')}_${$('ucs').value}`;}
function download(bytes,name,type){const url=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
async function exporting(kind){try{if(!report)throw new Error('Compare the current inputs first.');const snapshot=report,name=outputName();$('export-status').textContent='Preparing '+kind+'…';const bytes=kind==='xlsx'?await ReleasePackExport.xlsxBytes(snapshot):kind==='pdf'?ReleasePackExport.pdfBytes(snapshot):JSON.stringify(snapshot,null,2);if(report!==snapshot)throw new Error('Inputs changed while generating. Compare again before downloading.');download(bytes,name+'.'+kind,kind==='xlsx'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':kind==='pdf'?'application/pdf':'application/json');$('export-status').textContent='Downloaded review '+kind.toUpperCase()+'. Unresolved records remain visible; inspect private fields before sharing.';}catch(e){$('export-status').textContent='';err(e);}}
['xlsx','pdf','json'].forEach(kind=>$(kind).addEventListener('click',()=>exporting(kind)));
$('load-example').addEventListener('click',()=>{resetParse();$('metadata-file').value='';$('metadata').value=ReleasePackExample.csv;metadataLabel='synthetic-release.csv';$('delimiter').value=',';$('parse').click();$('column').value='0';$('inventory-source').value='manifest';$('inventory-source').dispatchEvent(new Event('change'));$('manifest').value=ReleasePackExample.paths.join('\n');$('mode').value='unique-basename';$('vendor-name').value='Marketfauna';$('library-name').value='Synthetic_Workshop';$('ucs').value='nonUCS';$('compare').click();});
$('compare').addEventListener('click',()=>{if(!report)return;$('inventory-rows').replaceChildren();for(const file of report.files)addRow($('inventory-rows'),[file.id,file.path,file.status,file.matchedBy.join(', ')||'none']);});
